### ISSUE TITLE
Hackintosh learning

### ISSUE THREAD

**Issue by rodgomesc** [kirainmoe/hasee-tongfang-macos#70]
congratulations for your dedication this project has evolved a lot since the last time I came here,

I am very curious to understand how certain things work, could you post some links on how you keep up to date on ssdt patches, good open core link references, tutorials, etc?

thanks

**Comment by kirainmoe** [comment]
Well, things about how to keep updating this repo can be a long story. But the simple reason is that you can always find something broken or imperfect, and dedicate to solving it. 

For knowing how the SSDT patches work, we need to have base knowledge about the ACPI. Writing a SSDT that make the device working from zero can be hard for us, but reading the decompiled source code of SSDT patches and figuring out the function is not so hard for those who have basic programming skill.

You should know that different SSDT patches have different functions. Some of them will be used for making the hardware work/be recognized by macOS, and some of then will be used for enabling some specific feature of macOS. The previous one is not general for all devices because the ACPI table difference between different manufactures, but a specific SSDT can work on the same barebones devices.  

I've learned a lot about how to patch DSDT/SSDT from [Rehabman's DSDT Patch Repo (very useful!)](https://github.com/RehabMan/Laptop-DSDT-Patch) and [OC-little (Chinese, English translation coming soon)](https://github.com/daliansky/OC-little/) when I was struggling to fix the battery status and USB. There are also many useful guides about patching the DSDT on tonymacx86.com and insanelymac.com forum. In China, there is another forum pcbeta.com . I learned from these forum in the early stage. Nowadays I still read on these forums to keep update to the latest macOS and OpenCore release. 

About how to configure the OpenCore, I personally recommend the guide [OpenCore Vanilla Desktop Guide](https://dortania.github.io/OpenCore-Desktop-Guide/), this is the best tutorial I've read. OpenCore is a fast-release bootloader, it will change a lot in every update, so we must update the config on the same time.

**Comment by kirainmoe** [comment]
I'm closing this issue, if you have any other problem just reopen this.
